url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

include:
  - _pages # All pages in folder will become html pages in root (due to permalinks)

# https://github.com/jekyll/jekyll/issues/5267#issuecomment-241379902
# exclude: [vendor] # unable to build a jekyll site … invalid date

exclude:
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

collections_dir: my_collections # gather collections inside collections_dir
collections:
  projects:
    output: true

plugins:
  - jekyll-redirect-from # https://github.com/jekyll/jekyll-redirect-from

whitelist:
  - jekyll-redirect-from # https://github.com/jekyll/jekyll-redirect-from